### PR TITLE
Improvements to CAF's config classes and parsers

### PR DESCRIPTION
**Pull request by Neverlord**

### CODE REVIEW

**Comment by josephnoir** [comment]
A few questions:
- The header for [Missing Duration Type](https://github.com/actor-framework/rfcs/blob/228bdf6b12cd0e2f5f4779b589a99e4f922687ef/proposals/0002-config-structuring-improvements.md#missing-duration-type) might have the wrong formatting? It looks like the headline for the whole section although the subsections are not related to it.
- How do pairs fit into the `config_value` definition, i.e., can a config value be a pair of config values and (if so) how do pairs and lists differ in their syntax?
- If we introduce read functionality, how would this interact with redefined values and would it be possible to append values to existing lists?
- How does this affect the command line interface?

**Comment by Neverlord** [comment]
> - The header for Missing Duration Type might have the wrong formatting?

You're right. Wrong heading type.

> - How do pairs fit into the `config_value` definition, i.e., can a config value be a pair of config values and (if so) how do pairs and lists differ in their syntax?

I would only add syntax for lists. A pair is simply a list with two elements. Reading a list into a C++ pair is then simply a matter of size and type checking. We could consider special notation for pairs/tuples, but I think it doesn't add anything besides complexity.

> - If we introduce read functionality, how would this interact with redefined values and would it be possible to append values to existing lists?

Good question. CAF currently appends to lists on assignment, but I'd prefer a more explicit notation to be honest. Maybe we can add an `+=`  operator or something along those lines.

> - How does this affect the command line interface?

The CLI parser should use the same syntax, e.g., `"--hosts=(sun, earth, mars)"`.

**Comment by lovemycatt** [comment]
In respect to the proposed syntax to assign a config grop as a key/value list:
       key=@other 
it would be a good thing that the [other] group does not generate an error if not exeplicitly declared in code.
Maybe a simple solution would be to have a specific syntax for defining "optional" groups in the ini file, that can be read at run-time, like [[other]].

It would also be useful to parse somehow lists of groups, such as in the following use case:

[[service_1]]
ip=192.178.20.3
port=1234
user=aaa

[[service_2]]
ip=192.178.20.10
port=1234
user=bbb

[data_sources]
get_data_from=@service_1, @service_2
...

**Comment by Neverlord** [comment]
> it would be a good thing that the [other] group does not generate an error if not exeplicitly declared in code.

True. Maybe the config should simply never print errors in the first place and store everything in a map. Users can then simply look at the content of the map to get some configured value (possibly user-requested name) dynamically at runtime. In this way, we souldn't need the `[[...]]` syntax.

> ```ini
> get_data_from=@service_1, @service_2
> ```

This should already work with the proposed list syntax when surrounding with `()`:

```ini
get_data_from=(@service_1, @service_2)
```

Or when concatenating groups into a single list:

```ini
full_list+=@some_group
full_list+=@some_other_group
; ...
```

**Comment by Neverlord** [comment]
@lovemycatt @josephnoir,

do you see any remaining issues with the proposal as it is now? Otherwise, I'd go ahead to merge it and create CAF issues for the required changes.

**Comment by lovemycatt** [comment]
The proposal in its last form seems perfectly consistent.

I just see two further improvements, not sure if pertinent to this thread:
1. Being able to "include" or "import" other ini's. This would help structuring large configurations.
2. Being able to expand environment variables (I see this mentioned in the 5223731 commit above.

**Comment by Neverlord** [comment]
@lovemycatt these improvements have already found their way into the latest proposal version:

See the [Includes section](https://github.com/actor-framework/rfcs/pull/2/files#diff-e581e75b7242c028a30c795278bb7270R167) of the proposal. The current idea is to have `!read` operate in the same way a C++ `#include` does, i.e., text replacement.

The [Accessing Variables](https://github.com/actor-framework/rfcs/pull/2/files#diff-e581e75b7242c028a30c795278bb7270R161) section says `variable`, but of course means *environment variable*. I'll tweak the text a bit to make this clear.

**Comment by josephnoir** [comment]
> do you see any remaining issues with the proposal as it is now? 

Nope, not from my side. Go ahead.

**Comment by Neverlord** [comment]
Ok, thanks for your feedback guys. I think further discussion should use our [development mailing list](https://groups.google.com/forum/#!forum/caf-devel).

**Pull request merged**
